### ISSUE TITLE
New icon URL does not work for signed out users

### ISSUE THREAD

**Issue by JakeWharton** [ghostty-org/.github#1]
It seems to bounce through the GitHub app for a redirect with temporary query parameters to provide access.

This also prevents it from working for users who are not in the beta, although that point is about to become moot.

Perhaps consider committing a version directly to this repo so it works for everyone?

**Comment by JakeWharton** [comment]
Me (Firefox):

![Image](https://github.com/user-attachments/assets/ded29ff8-ae97-4aa4-a7b2-8e2714c835dc)

Another user (Chrome):

![Image](https://github.com/user-attachments/assets/37dadea3-523a-4c4a-a98f-1e94052c3413)

Incognito (Firefox):

![Image](https://github.com/user-attachments/assets/18b9548a-628e-4133-b7f1-f3a7e081d35c)

**Comment by grndis** [comment]
Even the only file here is broken

**Comment by EgorWeders** [comment]
On signed too (firefox). Link leads to 404 error page

**Comment by JakeWharton** [comment]
Fixed by #3
